server:
  port: 11000
  servlet:
    context-path: /study-multi

management:
  endpoint.health.group.instance.include: diskSpace,ping

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQLInnoDBDialect
        show_sql: true  # sql 쿼리 표시
        format_sql: true  # 쿼리 포맷팅
        use_sql_comments: true  # sql 쿼리 추가정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://61.78.107.187:7777/study_hj # IP 라즈베리파이 임시 DB 상황보고 계속 쓸지말지 결정
    username: root
    password: dlsvy132@
  config:
    activate:
      on-profile: local
server.port: 11000

---
spring:
  config:
    activate:
      on-profile: dev
server.port: 8080

---
spring:
  config:
    activate:
      on-profile: stg
server.port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
server.port: 8080
